#!/usr/bin/env python3
"""TV Retention worker: RPC bridge for the web UI, and the scheduled retention run.

Production invocations come from Unraid's authenticated PHP bridge (`rpc`) or from the
plugin's own cron entry (`run --scheduled`). Nothing here trusts its input: every
request is re-validated, and every deletion is gated by the settings, the guards, and a
confirmed Sonarr match.
"""
from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import fcntl
import json
import os
import shutil
import subprocess
import sys
import urllib.parse
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from core import (DEFAULTS, MONITORING_MODES, keep_frame, REMOVAL_ACTIONS, VERSION, Rejected, atomic_json,
                  canonical_json, classify_monitoring, describe_lifecycle, describe_selectability,
                  effective_rule, evaluate, interpolate_air_dates, new_id, normalise, redact,
                  rule_fingerprint, validate_settings)
import alerts
from migrate import migrate
from sonarr import Sonarr, SonarrError, match_rule
import schedules
from store import (CONFIG, CRON, DEVELOPMENT, NAME, NOTIFY, RUNTIME, SCHEMA, UPDATE_CRON,
                   age_seconds, cache_path, clear_progress, episode_cache, forget_episodes,
                   invalidate_catalogue, job_state, journal, load_health, load_settings,
                   load_state, log_line, now_iso, read_cache, read_log, read_progress,
                   save_job_state, save_settings, save_state, set_progress, state_dir,
                   store_episodes, trim_health, write_cache)
from tmdb import TMDB, TMDBError, fill_air_dates

MAX_BROWSE_ENTRIES = 500
# Every minute: the tick is cheap, and a finer resolution means an hourly schedule set to
# :07 actually fires at :07 rather than at the next multiple of five.
# Sonarr is confirmed reachable this often, and before anything that needs it.
CONNECTIVITY_SECONDS = 300

TICK_CRON = '* * * * *'



# ---------------------------------------------------------------------------
# Environment guards
# ---------------------------------------------------------------------------

def array_ready() -> bool:
    if DEVELOPMENT:
        return True
    path = Path('/var/local/emhttp/var.ini')
    if not path.exists():
        return False
    return any(line.strip().strip(';') in ('mdState="STARTED"',) for line in path.read_text().splitlines())


def require_ready() -> None:
    if not array_ready():
        raise Rejected('The array is stopped. Start it before running TV Retention.')
    if not DEVELOPMENT and not Path('/mnt/user').is_mount():
        raise Rejected('Unraid user shares are not mounted.')


@contextlib.contextmanager
def run_lock(blocking: bool = False):
    """One run at a time. A scheduled run never overlaps a manual one."""
    RUNTIME.mkdir(parents=True, exist_ok=True)
    with open(RUNTIME / 'run.lock', 'a') as handle:
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | (0 if blocking else fcntl.LOCK_NB))
        except BlockingIOError:
            raise Rejected('A TV Retention run is already in progress.')
        yield


def notify(settings: dict, subject: str, description: str, importance: str = 'normal',
           event: str = 'errors') -> None:
    """Send an Unraid notification, if this kind of event is one the operator asked for."""
    wanted = (settings.get('notifications') or {}).get(event, True)
    if not wanted or DEVELOPMENT or not Path(NOTIFY).exists():
        return
    with contextlib.suppress(OSError, subprocess.SubprocessError):
        subprocess.run([NOTIFY, '-e', 'TV Retention', '-s', subject, '-d', description,
                        '-i', importance], timeout=20, check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# ---------------------------------------------------------------------------
# Scheduling
# ---------------------------------------------------------------------------

def write_cron(settings: dict) -> None:
    """Publish a fixed tick, and let the worker decide what is due.

    A generated crontab cannot express "the first Monday of the month", cannot notice a run
    missed while the server was off, and cannot hold a job back until Sonarr answers. The
    tick costs a few milliseconds when nothing is due and removes all three limits.
    """
    worker = f'/usr/bin/python3 /usr/local/emhttp/plugins/{NAME}/worker/main.py'
    try:
        CRON.parent.mkdir(parents=True, exist_ok=True)
        CRON.write_text(
            '# Generated by the TV Retention plugin. Schedules are set in Tools > TV Retention;\n'
            '# this entry only wakes the worker so it can decide what is due.\n'
            f'{TICK_CRON} {worker} tick 2>&1 | /usr/bin/logger -t {NAME}\n')
    except OSError as error:
        raise Rejected(f'Could not update the schedule file ({error})')
    if DEVELOPMENT or not Path(UPDATE_CRON).exists():
        return
    with contextlib.suppress(OSError, subprocess.SubprocessError):
        subprocess.run([UPDATE_CRON], timeout=30, check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# ---------------------------------------------------------------------------
# Sonarr helpers
# ---------------------------------------------------------------------------

def client_for(settings: dict, instance_id: str) -> Sonarr:
    for instance in settings.get('instances', []):
        if instance['id'] == instance_id:
            if not instance.get('enabled', True):
                raise Rejected(f'Sonarr instance "{instance["name"]}" is disabled.')
            return Sonarr(instance)
    raise Rejected('That Sonarr instance no longer exists.')


def bind_rules(settings: dict, force: bool = False) -> list:
    """Re-verify every rule against Sonarr and persist the result.

    A rule is only ever processed when it resolves to exactly one series, so a Sonarr
    outage or a renamed folder downgrades the rule to "unmatched" and stops it acting,
    rather than letting a run guess. The series list comes from the disk cache unless
    forced, because it is the most expensive call Sonarr offers.
    """
    report = []
    catalogues = {}
    for rule in settings.get('rules', []):
        try:
            if rule['instance_id'] not in catalogues:
                catalogues[rule['instance_id']] = catalogue_for(settings, rule['instance_id'], force=force)
            series = catalogues[rule['instance_id']]
        except (Rejected, SonarrError) as error:
            rule['match_status'] = 'unmatched'
            rule['match_error'] = str(error)
            report.append({'rule_id': rule['id'], 'ok': False, 'error': str(error)})
            continue
        outcome = match_rule(rule, series)
        if outcome.get('ok'):
            found = outcome['series']
            rule.update({
                'series_id': found['series_id'],
                'series_title': found['title'],
                'tvdb_id': found['tvdb_id'],
                'slug': found.get('slug') or '',
                'path': found['path'] or rule['path'],
                'match_status': 'matched',
                'match_error': '',
                'matched_at': now_iso(),
            })
            report.append({'rule_id': rule['id'], 'ok': True, 'how': outcome['how'],
                           'series_title': found['title'], 'path': found['path']})
        else:
            rule.update({'match_status': 'unmatched', 'match_error': outcome['error']})
            report.append({'rule_id': rule['id'], 'ok': False, 'error': outcome['error']})
    save_settings(settings)
    return report


def fill_from_history(client, series_id: int, episodes) -> int:
    """Date undated episodes from when Sonarr first acquired them.

    Reached only when a series has no dated episode at all, so interpolation had nothing
    to work from. Unlike the file's dateAdded, the oldest history record survives an
    upgrade, which is the flaw that made dateAdded a poor last resort.
    """
    missing = [episode for episode in episodes
               if not episode.get('air_date') and episode.get('has_file') and episode.get('episode_id')]
    if not missing:
        return 0
    try:
        earliest = client.first_acquired(series_id)
    except SonarrError:
        return 0
    filled = 0
    for episode in missing:
        stamp = earliest.get(episode['episode_id'])
        if not stamp:
            continue
        episode['air_date'] = str(stamp)[:10]
        episode['air_source'] = 'acquired'
        filled += 1
    return filled


def collect_episodes(settings: dict, rule: dict, client: Sonarr, tmdb) -> tuple:
    """Sonarr's episode files for one rule.

    Everything the retention pass needs — sizes, air dates, import dates, monitoring —
    arrives with the episodes. Sonarr owns the filesystem; the plugin only asks it what it
    has and tells it what to remove.
    """
    episodes = client.episodes(rule['series_id'])
    if tmdb and rule.get('tvdb_id'):
        with contextlib.suppress(TMDBError):
            fill_air_dates(episodes, tmdb, rule['tvdb_id'])
    if not interpolate_air_dates(episodes):
        fill_from_history(client, rule['series_id'], episodes)
    return episodes, [], []


# ---------------------------------------------------------------------------
# Deletion
# ---------------------------------------------------------------------------





def delete_one(settings: dict, rule: dict, client: Sonarr, episode: dict, dry_run: bool) -> dict:
    """Ask Sonarr to remove one episode file.

    Sonarr deletes the file, moves it to its recycle bin if it has one, takes the extra
    files it imported alongside, and tidies the folder if it is configured to. None of
    that is the plugin's business, and doing it here would only be a second, worse
    implementation of it.
    """
    action = {
        'path': episode['path'],
        'season': episode.get('season'),
        'episode': episode.get('episode'),
        'title': episode.get('title'),
        'air_date': episode.get('air_date'),
        'air_source': episode.get('air_source'),
        'size': episode.get('size'),
        'reason': episode.get('reason'),
        'dry_run': dry_run,
        'ok': True,
        'error': '',
    }
    if dry_run:
        return action
    try:
        client.delete_episode_file(episode['file_id'])
    except (SonarrError, ValueError) as error:
        action['ok'] = False
        action['error'] = str(error)
    return action


# ---------------------------------------------------------------------------
# Monitoring
# ---------------------------------------------------------------------------

def monitoring_mode(settings: dict, rule: dict) -> str:
    """How this rule treats Sonarr's monitored flags: 'unmonitor-only' or 'full-sync'.

    One global setting, overridable per series. There is deliberately no third value for
    "leave Sonarr alone": deleting a file while Sonarr still monitors it builds a
    fetch-and-delete loop, which is why unmonitoring on delete is an invariant here rather
    than a preference.
    """
    override = (rule or {}).get('monitoring') or ''
    if override in MONITORING_MODES:
        return override
    mode = ((settings.get('retention') or {}).get('monitoring') or '')
    return mode if mode in MONITORING_MODES else 'unmonitor-only'


def newly_scoped_rows(settings: dict, rule: dict, episodes: list, previous_scope) -> list:
    """Unmonitored episodes a save brought into the keep window that were outside it.

    A rule widened from thirty days to ninety did not ask for the ninety days it always
    had; it asked for the sixty it just gained. The two windows are compared rather than a
    list of ids being kept, because episodes move, and one that arrives belongs to
    whichever window it lands in.

    A series just added has no old window at all, so everything inside its keep window is
    newly scoped, which is what adding a series means.
    """
    frame = keep_frame(episodes, effective_rule(rule, settings.get('profiles')), settings)
    inside = [episode for episode in frame['in_frame'] if not episode.get('monitored')]
    if not previous_scope:
        return inside
    previous = dict(effective_rule(rule, settings.get('profiles')))
    previous.update(previous_scope)
    was = {episode.get('episode_id')
           for episode in keep_frame(episodes, previous, settings)['in_frame']}
    return [row for row in inside if row.get('episode_id') not in was]


def scope_pass(settings: dict, rule: dict, monitor_new: bool = False,
               unmonitor_outside: bool = False, previous_scope=None) -> dict:
    """Two one-time corrections, applied now rather than at the next run.

    Both are asked for explicitly, on a save, and neither deletes anything — they move
    Sonarr's monitored flags, which is reversible in a click and is the least destructive
    thing this plugin does.

    Waiting for the run is what makes the second one pointless. Every run already
    unmonitors what falls outside the window; the harm this prevents happens *between* the
    save and the run, when Sonarr is still fetching episodes the next run would delete. A
    queued version of it would arrive exactly too late to matter.

    Decided from the stored reading, so it costs one write to Sonarr and no reads.
    """
    episodes, series, read_at, from_cache = episodes_for(settings, rule, offline=True)
    active = effective_rule(rule, settings.get('profiles'))
    frame = keep_frame(episodes, active, settings)
    result = {'monitored': [], 'unmonitored': [], 'read_at': read_at}

    if monitor_new:
        result['monitored'] = newly_scoped_rows(settings, rule, episodes, previous_scope)
    if unmonitor_outside:
        result['unmonitored'] = [episode for episode in frame['out_frame'] if episode.get('monitored')]

    client = client_for(settings, rule['instance_id'])
    for key, wanted in (('monitored', True), ('unmonitored', False)):
        ids = [row['episode_id'] for row in result[key] if row.get('episode_id')]
        if ids:
            client.set_monitored(ids, wanted)
    if result['monitored'] and (settings.get('retention') or {}).get('search_after_monitor'):
        missing = [row['episode_id'] for row in result['monitored'] if not row.get('has_file')]
        if missing:
            with contextlib.suppress(SonarrError):
                client.search_episodes(missing)
    log_line(settings, 'info',
             f'{rule.get("series_title") or rule["path"]}: one-time pass monitored '
             f'{len(result["monitored"])}, unmonitored {len(result["unmonitored"])}')
    return {'monitored': len(result['monitored']), 'unmonitored': len(result['unmonitored'])}


def apply_removals(settings: dict, rules, dry_run: bool) -> list:
    """Carry out the removals queued against series, before anything else runs.

    A series being removed takes no part in the rest of the run: the decision to stop
    managing it has already been made, so evaluating its retention would be work nobody
    asked for. The plugin never deletes a series itself — options five and six ask Sonarr
    to, so Sonarr's own recycle bin and bookkeeping apply.
    """
    done = []
    for rule in rules:
        queued = (rule.get('queue') or {}).get('removal')
        if not queued:
            continue
        action = queued['action']
        record = {'rule_id': rule['id'], 'series_title': rule.get('series_title') or rule['path'],
                  'action': action, 'label': REMOVAL_ACTIONS.get(action, action),
                  'queued_at': queued.get('created_at'), 'dry_run': dry_run, 'ok': True, 'error': ''}
        if dry_run:
            done.append(record)
            continue
        try:
            client = client_for(settings, rule['instance_id'])
            if action in ('monitor-all', 'unmonitor-all'):
                episodes = client.episodes(rule['series_id'], files_only=False)
                client.set_monitored([e['episode_id'] for e in episodes], action == 'monitor-all')
            elif action == 'monitor-in-frame':
                state = monitoring_for(settings, rule, force=True)
                inside = [row['episode_id'] for row in state.get('in_frame_unmonitored') or []]
                client.set_monitored(inside, True)
            elif action in ('delete-series', 'delete-series-files'):
                client.delete_series(rule['series_id'], delete_files=(action == 'delete-series-files'))
                invalidate_catalogue(settings, rule['instance_id'])
                notify(settings, 'TV Retention removed a series',
                       f'{rule.get("series_title")}: {REMOVAL_ACTIONS[action].lower()}.',
                       'warning', event='series_removed')
        except (SonarrError, Rejected) as error:
            record.update(ok=False, error=str(error))
            done.append(record)
            continue
        log_line(settings, 'warning', f'removed {record["series_title"]}: {record["label"].lower()}')
        journal(settings, dict(record, at=now_iso()))
        done.append(record)
    return done


def monitoring_targets(settings: dict, state: dict, rule: dict) -> dict:
    """Which episodes a run will switch, under the mode this rule is running in.

    Unmonitoring is protection and monitoring is intent, which is the whole distinction
    the mode rests on. Unmonitoring only ever stops a download, so it happens in both
    modes: what leaves the keep window is unmonitored whether or not it has a file, and
    the fileless half matters most — an episode with a file is unmonitored when the file
    is deleted, but a missing one is never deleted, so nothing else would ever reach it,
    and Sonarr would go on fetching what the next run deletes.

    Monitoring can cost hundreds of gigabytes, so it happens only under full sync, or
    once, when someone asks for it on a rule they just widened.
    """
    inside = state.get('in_frame_unmonitored') or []
    outside = state.get('out_frame_monitored') or []
    wanted = inside if monitoring_mode(settings, rule) == 'full-sync' else []
    return {
        'monitor': [row['episode_id'] for row in wanted if row.get('episode_id')],
        'unmonitor': [row['episode_id'] for row in outside if row.get('episode_id')],
        'monitor_list': [row for row in wanted],
        'unmonitor_missing': len([row for row in outside if not row.get('has_file')]),
    }


def reconcile_monitoring(settings: dict, rule: dict, state: dict, dry_run: bool) -> dict:
    """Bring a series' monitoring in line with its keep window.

    Unmonitoring everything outside the window is unconditional and runs in both modes,
    including the episodes with no file: those are never deleted, so nothing else would
    ever unmonitor them, and Sonarr would go on fetching what the next run removes.

    Monitoring happens only under full sync. The one-time passes a save can ask for are
    applied at that moment, not here — waiting for a run is what made one of them useless.
    """
    targets = monitoring_targets(settings, state, rule)
    monitor = list(targets['monitor'])
    monitor_list = list(targets['monitor_list'])
    result = {'monitored': len(monitor), 'unmonitored': len(targets['unmonitor']),
              'searched': 0, 'error': '', 'newly_scoped': 0,
              'monitor_list': monitor_list,
              'unmonitor_list': list(state.get('out_frame_monitored') or [])}
    if dry_run:
        return result
    try:
        client = client_for(settings, rule['instance_id'])
        if targets['unmonitor']:
            client.set_monitored(targets['unmonitor'], False)
        if monitor:
            client.set_monitored(monitor, True)
            if (settings.get('retention') or {}).get('search_after_monitor'):
                # Only the episodes that have no file: searching one already on disk would
                # ask Sonarr to look for an upgrade nobody requested.
                missing = [row['episode_id'] for row in monitor_list
                           if not row.get('has_file') and row.get('episode_id')]
                if missing:
                    client.search_episodes(missing)
                    result['searched'] = len(missing)
    except SonarrError as error:
        result['error'] = str(error)
    return result


def process_rule(settings: dict, rule: dict, tmdb, dry_run: bool) -> dict:
    """Evaluate and (unless previewing) execute one rule."""
    outcome = {
        'rule_id': rule['id'],
        'series_title': rule.get('series_title') or rule['path'],
        'path': rule['path'],
        'preset': '',
        'ok': True,
        'error': '',
        'note': '',
        'blocked': None,
        'considered': 0,
        'deleted': [],
        'kept': 0,
        'protected': 0,
        'freed_bytes': 0,
        'unmonitored': 0,
        'unmonitored_frame': 0,
        'monitored': 0,
        'monitor_list': [],
        'unmonitor_list': [],
        'searched': 0,
        'newly_scoped': 0,
    }
    if rule.get('match_status') != 'matched':
        outcome.update(ok=False, error=rule.get('match_error') or 'Rule is not matched to a Sonarr series')
        return outcome
    try:
        active = effective_rule(rule, settings.get('profiles'))
    except Rejected as error:
        outcome.update(ok=False, error=str(error))
        return outcome
    outcome['preset'] = active.get('profile_name', '')
    client = client_for(settings, rule['instance_id'])
    try:
        episodes, missing, unknown = collect_episodes(settings, rule, client, tmdb)
    except SonarrError as error:
        outcome.update(ok=False, error=str(error))
        return outcome

    # Phase one: bring monitoring in line with the keep window, before anything is
    # removed. Doing it first means the run leaves Sonarr consistent even if the deletion
    # pass is stopped by a guard.
    # A run reads Sonarr for itself. Everything it is about to change is decided here, and
    # a stored reading is the one thing that must not stand behind a write.
    reconciled = reconcile_monitoring(settings, rule, monitoring_for(settings, rule, force=True), dry_run)
    outcome['monitored'] = reconciled['monitored']
    outcome['unmonitored_frame'] = reconciled['unmonitored']
    outcome['searched'] = reconciled['searched']
    outcome['newly_scoped'] = reconciled.get('newly_scoped', 0)
    # The episodes themselves, so a detail view can list every change rather than only
    # the deletions.
    outcome['monitor_list'] = reconciled.get('monitor_list') or []
    outcome['unmonitor_list'] = reconciled.get('unmonitor_list') or []
    if reconciled['error']:
        outcome['error'] = reconciled['error']

    decision = evaluate(episodes, active, settings)
    outcome['considered'] = decision['considered']
    outcome['kept'] = len(decision['keep'])
    outcome['protected'] = len(decision['protected'])
    if decision['blocked']:
        outcome['blocked'] = decision['blocked']
        return outcome

    deleted, deleted_ids = [], []
    for episode in decision['delete']:
        action = delete_one(settings, rule, client, episode, dry_run)
        outcome['deleted'].append(action)
        if action['ok']:
            outcome['freed_bytes'] += int(episode.get('size') or 0)
            deleted_ids.append(episode.get('episode_id'))
            deleted.append(episode)
        else:
            outcome['ok'] = False
            outcome['error'] = action['error']

    if deleted_ids and not dry_run:
        # Not optional, and not a setting. Deleting a file while leaving the episode
        # monitored guarantees Sonarr fetches it again and the next run deletes it again.
        # The monitoring mode governs the episodes around it, never this.
        try:
            client.unmonitor(deleted_ids)
            outcome['unmonitored'] = len(deleted_ids)
        except SonarrError as error:
            outcome['error'] = f'Files removed, but unmonitoring failed: {error}'
        if (settings.get('recycle') or {}).get('mode') == 'plugin':
            # Moving files out of the library is invisible to Sonarr until it rescans.
            with contextlib.suppress(SonarrError):
                client.rescan(rule['series_id'])

    return outcome


def run(preview: bool = False, rule_ids=None, scheduled: bool = False) -> dict:
    """Evaluate every enabled rule, and delete unless previewing or in dry-run mode."""
    require_ready()
    settings = load_settings()
    log_line(settings, 'info',
             ('scheduled ' if scheduled else '') + ('preview' if preview else 'run') + ' started')
    # A manual run is always live; Test Mode governs the scheduler alone, and the preview
    # flag is the read-only plan behind "Show scheduled changes".
    test_mode = scheduled and bool((settings.get('schedule') or {}).get('test_mode', True))
    dry_run = preview or test_mode
    started = now_iso()
    clock = time.monotonic()

    bind_rules(settings)
    tmdb = None
    tmdb_cfg = settings.get('tmdb') or {}
    if tmdb_cfg.get('enabled') and tmdb_cfg.get('api_key'):
        tmdb = TMDB(tmdb_cfg['api_key'], cache_path=state_dir(settings) / 'tmdb-cache.json')

    selected = [r for r in settings.get('rules', []) if r.get('enabled')]
    if rule_ids:
        selected = [r for r in selected if r['id'] in set(rule_ids)]

    # Phase one: queued removals. A series leaving takes no further part in this run,
    # because the decision to stop managing it has already been made.
    removals = apply_removals(settings, selected, dry_run)
    if removals and not dry_run:
        removed = {record['rule_id'] for record in removals if record['ok']}
        settings['rules'] = [r for r in settings.get('rules', []) if r['id'] not in removed]
        save_settings(settings)
        health = load_health(settings)
        for rule_id in removed:
            health['rules'].pop(rule_id, None)
        health['alerts'] = [a for a in (health.get('alerts') or []) if a.get('rule_id') not in removed]
        write_cache(settings, 'health.json', health)
        selected = [r for r in selected if r['id'] not in removed]

    results, planned = [], []
    for rule in selected:
        try:
            results.append(process_rule(settings, rule, tmdb, dry_run=True))
        except Rejected as error:
            results.append({'rule_id': rule['id'], 'series_title': rule.get('series_title') or rule['path'],
                            'path': rule['path'], 'ok': False, 'error': str(error), 'deleted': [],
                            'considered': 0, 'kept': 0, 'protected': 0,
                            'blocked': None, 'freed_bytes': 0, 'unmonitored': 0,
                            'preset': '', 'note': ''})
    total = sum(len(result['deleted']) for result in results)

    summary = {
        'id': new_id(),
        'started': started,
        'finished': now_iso(),
        'scheduled': scheduled,
        'preview': preview,
        'test_mode': test_mode,
        'dry_run': dry_run,
        'rules': results,
        'planned': total,
        'removals': removals,
        'deleted': 0,
        'freed_bytes': 0,
        'errors': [r['error'] for r in results if r.get('error')],
        'blocked': [r['blocked'] for r in results if r.get('blocked')],
        'duration_seconds': 0,
    }

    if not preview and not dry_run:
        # Second pass: the plan is re-derived immediately before acting, so a file that
        # changed between planning and execution is judged on its current state.
        executed = []
        for rule in selected:
            try:
                executed.append(process_rule(settings, rule, tmdb, dry_run=False))
            except Rejected as error:
                executed.append({'rule_id': rule['id'], 'series_title': rule.get('series_title') or rule['path'],
                                 'path': rule['path'], 'ok': False, 'error': str(error), 'deleted': [],
                                 'considered': 0, 'kept': 0, 'protected': 0,
                                 'blocked': None, 'freed_bytes': 0, 'unmonitored': 0,
                                 'preset': '', 'note': ''})
        summary['rules'] = executed
        summary['deleted'] = sum(len([d for d in r['deleted'] if d['ok']]) for r in executed)
        summary['freed_bytes'] = sum(r['freed_bytes'] for r in executed)
        summary['errors'] = [r['error'] for r in executed if r.get('error')]
        summary['blocked'] = [r['blocked'] for r in executed if r.get('blocked')]
        # Deleting unmonitors, so any cached monitoring for those shows is now wrong.
        for result in executed:
            if not result.get('deleted') and not result.get('unmonitored'):
                continue
            rule = next((r for r in selected if r['id'] == result['rule_id']), None)
            if rule:
                with contextlib.suppress(Rejected, SonarrError):
                    record_monitoring(settings, rule, monitoring_for(settings, rule, force=True))

    summary['finished'] = now_iso()
    summary['duration_seconds'] = round(time.monotonic() - clock, 1)

    if not preview:
        state = load_state(settings)
        state['runs'] = state.get('runs', []) + [{
            'id': summary['id'], 'started': summary['started'], 'finished': summary['finished'],
            'scheduled': scheduled, 'dry_run': dry_run, 'planned': summary['planned'],
            'deleted': summary['deleted'], 'freed_bytes': summary['freed_bytes'],
            'errors': summary['errors'][:10],
        }]
        state['last_run'] = summary
        save_state(settings, state)
        journal(settings, summary)
        log_line(settings, 'warning',
                 ('[TEST MODE] ' if test_mode else '')
                 + f'run finished: {summary["planned"]} planned, {summary["deleted"]} deleted, '
                 + f'{summary["freed_bytes"] // 1024 // 1024} MiB')
        if summary['errors']:
            notify(settings, 'TV Retention finished with errors', '; '.join(summary['errors'])[:400],
                   'warning', event='errors')
        elif test_mode:
            # A test run notifies exactly as a real one would: that is how you learn the
            # schedule fired correctly at four in the morning.
            notify(settings, '[TEST MODE] TV Retention scheduled run',
                   f'{summary["planned"]} file(s) would have been removed. Nothing was changed.',
                   event='run_completed')
        elif summary['deleted']:
            gigabytes = summary['freed_bytes'] / 1024 ** 3
            notify(settings, 'TV Retention removed old episodes',
                   f'{summary["deleted"]} files removed, {gigabytes:.1f} GiB reclaimed.',
                   event='run_completed')
    return summary


def catalogue_for(settings: dict, instance_id: str, force: bool = False) -> list:
    """The instance's series list, cached on disk.

    Served from the store, never on a timer. The sync is what refreshes it, so browsing
    three thousand series costs a file read and the interface never waits on Sonarr. It is
    fetched here only when there is nothing stored at all — a first run, or a mapping
    change that retired what was — because an empty picker is worse than a pause.

    The store holds *mapped* series, so it is keyed by the mapping's shape: a field added
    without that key moving reads as absent everywhere until the entry is replaced. That
    is exactly how the ended pill stayed blank once before.
    """
    cache = read_cache(settings, 'catalogue.json')
    entry = cache.get(instance_id) or {}
    stored = entry.get('series') if entry.get('schema') == SCHEMA else None
    if stored and not force:
        return stored
    series = client_for(settings, instance_id).series()
    cache[instance_id] = {'schema': SCHEMA, 'fetched_at': now_iso(), 'series': series}
    write_cache(settings, 'catalogue.json', cache)
    return series


def series_record(settings: dict, rule: dict) -> dict:
    """The rule's series, from the store, or read on its own if it is not there yet."""
    entry = read_cache(settings, 'catalogue.json').get(rule.get('instance_id')) or {}
    if entry.get('schema') == SCHEMA:
        for series in entry.get('series') or []:
            if series.get('series_id') == rule.get('series_id'):
                return series
    # Not in the store: a series added since the last sync, being read on demand.
    try:
        return client_for(settings, rule['instance_id']).series_one(rule['series_id'])
    except Rejected:
        return {}


def episodes_for(settings: dict, rule: dict, force: bool = False, offline: bool = False) -> tuple:
    """One rule's reading of Sonarr: its episodes, its series record, and when it was read.

    Fetches when asked to, when nothing is stored, or when what is stored has aged past
    the health TTL. Otherwise the stored reading is returned with its true age, so a plan
    computed from it can be shown as what it is: current arithmetic over a known-old read.

    The series record is stored with the episodes rather than read separately, or serving
    a cached reading would still cost a call — a small one, but one per series per check.
    """
    cached, series, fetched_at = episode_cache(settings, rule)
    ttl = int((settings.get('health') or {}).get('ttl_hours', 24)) * 3600
    age = age_seconds(fetched_at)
    if not force and cached and age is not None and age < ttl:
        return cached, series, fetched_at, True
    if offline:
        # The TTL governs when to fetch, not what may be used: an old reading shown with
        # its true age beats no reading at all, and the caller promised not to go out.
        if not cached:
            raise Rejected('Nothing has been read for this series yet.')
        return cached, series, fetched_at, True
    client = client_for(settings, rule['instance_id'])
    episodes = client.episodes(rule['series_id'], files_only=False)
    if not interpolate_air_dates(episodes):
        fill_from_history(client, rule['series_id'], episodes)
    series = series_record(settings, rule)
    return episodes, series, store_episodes(settings, rule, episodes, series), False


def sync_from_sonarr(settings: dict, reason: str = 'scheduled') -> dict:
    """Read Sonarr once, store what it says, and report what moved.

    This is the only place the plugin reads Sonarr without being asked to. Everything the
    interface does — browsing series, widening a keep window, deciding what a run would
    delete — is answered from what this leaves behind, so the page never waits on Sonarr
    and a rule edited at midnight costs nothing at all.

    Series come at series level for the whole library, because that payload already
    carries seasons, episode counts, sizes and air dates: everything a list or a grid
    wants. Episodes come only for series under a rule, because only a retention decision
    needs them, and any other series can be read on demand in about thirty milliseconds.

    Nothing is written unless it differs. The comparison saves no network — a change to a
    monitored flag is invisible until the episodes are read — but it says what changed
    since yesterday, which is worth more than the writes it avoids.
    """
    started = now_iso()
    report = {'started': started, 'reason': reason, 'series_added': [], 'series_removed': 0,
              'series_changed': 0, 'episodes_changed': [], 'errors': []}
    catalogue = read_cache(settings, 'catalogue.json')

    for instance in settings.get('instances', []):
        if not instance.get('enabled', True):
            continue
        try:
            fresh = Sonarr(instance).series()
        except Rejected as error:
            report['errors'].append(f'{instance["name"]}: {error}')
            continue
        entry = catalogue.get(instance['id']) or {}
        previous = {series['series_id']: series for series in (entry.get('series') or [])
                    if entry.get('schema') == SCHEMA}
        for series in fresh:
            was = previous.get(series['series_id'])
            if was is None:
                # Only news on a library we have seen before; the first sync is the
                # baseline, and announcing three thousand series is true and useless.
                if previous:
                    report['series_added'].append(series['title'])
            elif canonical_json(was) != canonical_json(series):
                report['series_changed'] += 1
        report['series_removed'] += len(set(previous) - {s['series_id'] for s in fresh})
        catalogue[instance['id']] = {'schema': SCHEMA, 'fetched_at': now_iso(), 'series': fresh}

    write_cache(settings, 'catalogue.json', catalogue)

    for rule in settings.get('rules', []):
        if not rule.get('enabled') or rule.get('match_status') != 'matched':
            continue
        try:
            client = client_for(settings, rule['instance_id'])
            episodes = client.episodes(rule['series_id'], files_only=False)
            if not interpolate_air_dates(episodes):
                fill_from_history(client, rule['series_id'], episodes)
        except Rejected as error:
            report['errors'].append(f'{rule.get("series_title") or rule["path"]}: {error}')
            continue
        stored, _, _ = episode_cache(settings, rule)
        if stored is None or canonical_json(stored) != canonical_json(episodes):
            report['episodes_changed'].append(rule.get('series_title') or rule['path'])
        store_episodes(settings, rule, episodes, series_record(settings, rule))
        with contextlib.suppress(Rejected, SonarrError):
            check_one_rule(settings, rule)

    mark_synced(settings, report)
    if report['series_added']:
        names = ', '.join(report['series_added'][:8])
        notify(settings, f'Sonarr added {len(report["series_added"])} series',
               f'{names}. Add a rule in TV Retention if you want retention applied.',
               event='series_added')
    log_line(settings, 'info',
             f'sync ({reason}): {report["series_changed"]} series changed, '
             f'{len(report["series_added"])} added, {report["series_removed"]} removed, '
             f'{len(report["episodes_changed"])} of the managed series moved')
    return report


def mark_synced(settings: dict, report: dict) -> None:
    write_cache(settings, 'sync.json', dict(report, synced_at=now_iso()))


def last_sync(settings: dict) -> dict:
    return read_cache(settings, 'sync.json')


def sync_is_due(settings: dict) -> bool:
    """True when the stored reading has aged past the interval, or there is none."""
    age = age_seconds(last_sync(settings).get('synced_at'))
    return age is None or age > int((settings.get('health') or {}).get('ttl_hours', 24)) * 3600


def recompute_plans(settings: dict, health: dict) -> int:
    """Re-decide every rule from the reading already stored. No network at all.

    Time moves a keep window on its own: an episode inside it this morning is outside it
    tonight, and a page left open would otherwise go on showing the plan it was handed
    when it loaded. Deciding is arithmetic — the whole library in a few hundredths of a
    second — so the page can afford to do it on every heartbeat. Nothing is written unless
    a rule's result actually differs, or an open page would rewrite the cache every
    fifteen seconds to say nothing had changed.
    """
    changed = 0
    for rule in settings.get('rules', []):
        if not rule.get('enabled'):
            continue
        try:
            fresh = monitoring_for(settings, rule, offline=True)
        except Rejected:
            continue          # never read; the check queue will fetch it
        if not fresh.get('ok'):
            continue
        fresh['fingerprint'] = rule_fingerprint(rule, settings)
        previous = (health.get('rules') or {}).get(rule['id']) or {}
        # Compared with the old timestamp in place, so "nothing changed" is about the
        # result and not about when it was worked out.
        fresh['checked_at'] = previous.get('checked_at') or now_iso()
        if canonical_json(fresh) == canonical_json(previous):
            continue
        fresh['checked_at'] = now_iso()
        health.setdefault('rules', {})[rule['id']] = fresh
        others = [alert for alert in (health.get('alerts') or []) if alert.get('rule_id') != rule['id']]
        health['alerts'] = alerts.merge(health.get('alerts') or [],
                                        others + alerts_for_rule(settings, rule, fresh))
        changed += 1
    return changed

def log_settings_change(settings: dict, previous: dict, updated: dict) -> None:
    """Say what a save actually changed, so the log answers "when did this become true?"."""
    for key in ('schedule', 'retention', 'logging', 'notifications', 'health', 'alerts',
                'state_dir', 'log_retention_runs', 'instances', 'profiles', 'rules', 'tmdb'):
        if canonical_json(previous.get(key)) == canonical_json(updated.get(key)):
            continue
        if key == 'schedule':
            log_line(settings, 'info', 'schedule saved: '
                     + (schedules.describe(updated.get('schedule') or {})
                        if (updated.get('schedule') or {}).get('enabled') else 'disabled'))
        elif key in ('instances', 'profiles', 'rules'):
            log_line(settings, 'info', f'{key} changed: {len(previous.get(key) or [])} '
                                       f'-> {len(updated.get(key) or [])}')
        else:
            log_line(settings, 'info', f'{key} settings saved')


def announce_alerts(settings: dict, previous: list, current: list) -> list:
    """Notify about problems that were not there before.

    Alerts are keyed and carry their own first-seen date, so "new" is a question about the
    keys, not about the check that happened to find them: a condition that has been true
    since Tuesday is not announced again on Wednesday.

    What is worth announcing is a property of the alert's kind: something structurally
    wrong — a series that cannot be found, a binding that moved, a Sonarr that will not
    answer. Never the retention itself, which is the job, not the news.
    """
    # A muted kind is not notified about either. Saying "never show me this" and then
    # sending it to the notification centre would be the plugin arguing with the operator.
    muted = set(((settings.get('alerts') or {}).get('muted')) or [])
    known = {alert['key'] for alert in previous or []}
    fresh = [alert for alert in current or []
             if alert['key'] not in known and alerts.notifies(alert)
             and alert.get('kind') not in muted]
    for alert in fresh:
        notify(settings, f'TV Retention: {alert["title"]}',
               f'{alert.get("detail") or alert.get("help") or ""}'.strip()[:600],
               'warning' if alert['severity'] == alerts.ERROR else 'normal',
               event='health_problems')
        log_line(settings, 'warning', f'{alert["title"]} — {alert.get("detail", "")}')
    return fresh



def stale_rule_ids(settings: dict, health: dict) -> list:
    """The enabled rules whose cached result is missing, outdated, or no longer applicable.

    Only these are re-read when the page opens. Everything else is served from the cache,
    which is the whole point of keeping one.
    """
    ttl = int(settings.get('health', {}).get('ttl_hours', 24)) * 3600
    dirty = set(health.get('dirty') or [])
    stale = []
    for rule in settings.get('rules', []):
        if not rule.get('enabled'):
            continue
        # Sonarr reported a change to this series: nothing cached for it can be trusted,
        # whatever its age says.
        if rule['id'] in dirty:
            stale.append(rule['id'])
            continue
        entry = (health.get('rules') or {}).get(rule['id'])
        if not entry:
            stale.append(rule['id'])
            continue
        try:
            if entry.get('fingerprint') != rule_fingerprint(rule, settings):
                stale.append(rule['id'])
                continue
        except Rejected:
            stale.append(rule['id'])
            continue
        age = age_seconds(entry.get('checked_at'))
        if age is None or age > ttl:
            stale.append(rule['id'])
    return stale


def health_is_stale(settings: dict, health: dict) -> bool:
    """True when any enabled rule has no usable cached result."""
    return bool(stale_rule_ids(settings, health))


def record_monitoring(settings: dict, rule: dict, state: dict) -> None:
    """Store one rule's monitoring result. Called by the health check and by every run,
    so a library that is checked nightly costs nothing extra to keep current."""
    health = load_health(settings)
    health['rules'][rule['id']] = dict(state, checked_at=now_iso(),
                                       fingerprint=rule_fingerprint(rule, settings))
    write_cache(settings, 'health.json', health)


# ---------------------------------------------------------------------------
# Connectivity
# ---------------------------------------------------------------------------

def sonarr_reachable(settings: dict) -> bool:
    """Whether every enabled instance answered its last connectivity check."""
    health = load_health(settings)
    instances = health.get('instances') or {}
    for instance in settings.get('instances', []):
        if not instance.get('enabled', True):
            continue
        state = instances.get(instance['id'])
        if not state or not state.get('reachable', state.get('ok', False)):
            return False
    return True


def check_connectivity(settings: dict) -> bool:
    """Ask each enabled instance whether it is there. Cheap: one status call each."""
    health = load_health(settings)
    health.setdefault('instances', {})
    everything_up = True
    for instance in settings.get('instances', []):
        entry = dict(health['instances'].get(instance['id']) or {},
                     instance_id=instance['id'], name=instance['name'],
                     checked_at=now_iso())
        if not instance.get('enabled', True):
            entry.update(reachable=True, disabled=True, error='')
            health['instances'][instance['id']] = entry
            continue
        try:
            version = Sonarr(instance).status().get('version', '')
            was_down = entry.get('reachable') is False
            entry.update(reachable=True, ok=entry.get('ok', True), error='', sonarr_version=version)
            if was_down:
                log_line(settings, 'warning', f'{instance["name"]} is reachable again')
        except (SonarrError, Rejected) as error:
            everything_up = False
            if entry.get('reachable') is not False:
                log_line(settings, 'error', f'{instance["name"]} is unreachable: {error}')
            entry.update(reachable=False, ok=False, error=str(error))
        health['instances'][instance['id']] = entry
    write_cache(settings, 'health.json', health)
    return everything_up


def check_one_rule(settings: dict, rule: dict, instance_state: dict = None, force: bool = False) -> dict:
    """Verify one rule, cache the result, and refresh that rule's alerts.

    Only this rule's alerts are replaced; everything else in the set is left alone, so a
    single-series recheck cannot clear a problem it never looked at.
    """
    health = load_health(settings)
    dirty = list(health.get('dirty') or [])
    if instance_state and not instance_state.get('ok', True):
        state = {'rule_id': rule['id'], 'series_title': rule.get('series_title') or rule['path'],
                 'ok': False, 'status': 'unmatched', 'label': 'Sonarr unavailable',
                 'error': instance_state.get('error', ''), 'checked_at': now_iso(),
                 'fingerprint': rule_fingerprint(rule, settings)}
    else:
        # A series Sonarr says changed is re-read whatever its age; everything else is
        # re-decided from what is already stored, which costs no call at all.
        state = monitoring_for(settings, rule, force=force or rule['id'] in dirty)
        state['checked_at'] = now_iso()
        state['fingerprint'] = rule_fingerprint(rule, settings)
    if rule['id'] in dirty and not state.get('from_cache') and state.get('ok'):
        health['dirty'] = [known for known in dirty if known != rule['id']]
    # The running commentary a person reads while something is happening. A read from
    # Sonarr is worth a line; one served from the store is detail.
    plan = state.get('plan') or {}
    summary = (f'{plan.get("delete", 0)} to delete, {plan.get("monitor", 0)} to monitor, '
               f'{plan.get("unmonitor", 0)} to unmonitor')
    log_line(settings, 'verbose' if state.get('from_cache') else 'info',
             f'checked {state.get("series_title")}: {summary}'
             + (' (from the stored reading)' if state.get('from_cache') else ' (read from Sonarr)'))
    was = (health.get('rules') or {}).get(rule['id']) or {}
    # Said once, when Sonarr first reports it, rather than on every check thereafter.
    if state.get('ended') and not was.get('ended'):
        notify(settings, 'A series has ended',
               f'Sonarr reports {state.get("series_title")} as ended'
               + (' and nothing remains inside its keep window.'
                  if state.get('retention_expired') else '.'),
               event='series_ended')
        log_line(settings, 'warning', f'{state.get("series_title")} has ended in Sonarr')
    health['rules'][rule['id']] = state
    others = [alert for alert in (health.get('alerts') or []) if alert.get('rule_id') != rule['id']]
    health['alerts'] = alerts.merge(health.get('alerts') or [],
                                    others + alerts_for_rule(settings, rule, state))
    write_cache(settings, 'health.json', health)
    return state


# ---------------------------------------------------------------------------
# Scheduled health check
# ---------------------------------------------------------------------------

def check_instance(settings: dict, instance: dict, force: bool = True) -> dict:
    """Reachability, credentials, and whether Sonarr has somewhere to put deleted files."""
    result = {'instance_id': instance['id'], 'name': instance['name'], 'ok': True,
              'error': '', 'checked_at': now_iso(), 'reachable': True}
    if not instance.get('enabled', True):
        return dict(result, disabled=True)
    try:
        client = Sonarr(instance)
        status = client.status()
        catalogue = catalogue_for(settings, instance['id'], force=force)
    except (SonarrError, Rejected) as error:
        return dict(result, ok=False, reachable=False, error=str(error))
    result['sonarr_version'] = status.get('version')
    result['series_count'] = len(catalogue)
    result['recycle_bin'] = check_recycle_bin(settings, instance)
    return result


def alerts_for_rule(settings: dict, rule: dict, state: dict) -> list:
    """Turn one rule's checked state into the alerts it warrants.

    Monitoring drift is deliberately absent. Every run reconciles the whole keep window,
    so an alert about it would be a warning that the next run silently fixes — and the
    scheduled-changes line already says what that run will do, which is the useful form of
    the same information.
    """
    if rule.get('match_status') != 'matched':
        return [alerts.make('unmatched', rule_id=rule['id'],
                            detail=rule.get('match_error') or 'No Sonarr series resolves to this rule')]
    if not state.get('ok'):
        return [alerts.make('unmatched', rule_id=rule['id'],
                            detail=state.get('error') or state.get('label') or 'Could not read Sonarr')]
    if state.get('lifecycle') in ('ended_expired', 'ended_empty'):
        return [alerts.make('ended-expired', rule_id=rule['id'],
                            detail='Sonarr reports this series as ended and nothing remains '
                                   'inside the keep window')]
    return []


def system_alerts(settings: dict, health: dict) -> list:
    """Alerts about the installation rather than about one series."""
    found = []
    for instance in settings.get('instances', []):
        if not instance.get('enabled', True):
            continue
        state = (health.get('instances') or {}).get(instance['id']) or {}
        if state.get('reachable') is False:
            found.append(alerts.make('sonarr-unreachable', instance_id=instance['id'],
                                     detail=f'{instance["name"]}: {state.get("error", "no answer")}'))
            continue
        if not state.get('recycle_bin'):
            found.append(alerts.make('no-recycle-bin', instance_id=instance['id'],
                                     detail=f'{instance["name"]} deletes files outright; nothing is recoverable'))
    return found


def run_health_check(scheduled: bool = False, force: bool = True) -> dict:
    """Verify instances, matches, folders, and monitoring, and cache the results.

    Read-only against both Sonarr and the filesystem: it never deletes and never changes a
    monitored flag. Progress is published rule by rule, so an interface open while this
    runs can show each show updating instead of waiting for the whole sweep.
    """
    require_ready()
    settings = load_settings()
    started = now_iso()
    clock = time.monotonic()
    health = load_health(settings)
    rules = [rule for rule in settings.get('rules', []) if rule.get('enabled')]
    set_progress(settings, running=True, started=started, scheduled=scheduled,
                 total=len(rules), done=0, current='', current_title='',
                 phase='instances')
    try:
        instances = {}
        for instance in settings.get('instances', []):
            instances[instance['id']] = check_instance(settings, instance, force=force)
        health['instances'] = instances
        write_cache(settings, 'health.json', health)

        set_progress(settings, phase='matching')
        bind_rules(settings, force=force)
        settings = load_settings()
        rules = [rule for rule in settings.get('rules', []) if rule.get('enabled')]
        set_progress(settings, phase='rules', total=len(rules))

        found, checked = [], 0
        found.extend(system_alerts(settings, health))
        for rule in rules:
            set_progress(settings, done=checked, current=rule['id'],
                         current_title=rule.get('series_title') or rule['path'])
            # The scheduled sweep is the backstop: it reads every series outright, which
            # is what catches monitoring toggled by hand in Sonarr — the one change no
            # cheap signal reports. Fourteen megabytes and about a second, once a day.
            state = check_one_rule(settings, rule, instances.get(rule['instance_id']), force=force)
            checked += 1
            found.extend(alerts_for_rule(settings, rule, state))

        health = load_health(settings)
        # Results for rules that no longer exist would otherwise accumulate for ever and
        # make the counts disagree with the list on screen.
        live = {rule['id'] for rule in settings.get('rules', [])}
        for gone in set(health.get('rules') or {}) - live:
            forget_episodes(settings, gone)
        health['rules'] = {rid: entry for rid, entry in (health.get('rules') or {}).items() if rid in live}
        health['dirty'] = [rid for rid in (health.get('dirty') or []) if rid in live]
        previous = health.get('alerts') or []
        cleared = alerts.resolved(previous, found)
        health['alerts'] = alerts.merge(previous, found)
        health['checked_at'] = started
        health['duration_seconds'] = round(time.monotonic() - clock, 1)
        health['scheduled'] = scheduled
        health['rules_checked'] = checked
        write_cache(settings, 'health.json', health)
    finally:
        clear_progress(settings)

    for alert in cleared:
        log_line(settings, 'warning', f'resolved: {alert["title"]} — {alert.get("detail", "")}')
    reportable = alerts.managed_only(health['alerts'], settings)
    summary = alerts.summarise(reportable)
    # One notification per problem, the first time it appears. The summary this replaced
    # was re-sent by every sweep for as long as the problem stayed true, so a Sonarr that
    # had been unreachable since Tuesday said so again every day — which teaches people to
    # ignore the notification that matters.
    announced = announce_alerts(settings, alerts.managed_only(previous, settings), reportable)
    if not announced and not summary['error'] and scheduled:
        notify(settings, 'TV Retention health check passed',
               f'{checked} rule(s) verified against Sonarr.', event='health_ok')
    log_line(settings, 'warning' if summary['error'] else 'verbose',
             f'series match check: {checked} rule(s), {summary["error"]} error(s), '
             f'{summary["warning"]} warning(s)')
    return health




def tick() -> int:
    """Decide what is due and do it. Invoked every minute by the plugin's cron entry.

    Nothing here is expensive unless something is actually due: the common case is reading
    two small files and comparing timestamps.
    """
    settings = load_settings()
    if not array_ready():
        return 0
    now = dt.datetime.now(dt.timezone.utc)
    state = job_state(settings)
    actions = []

    connectivity = CONNECTIVITY_SECONDS
    if age_seconds(state.get('last_connectivity')) is None or \
            age_seconds(state.get('last_connectivity')) >= connectivity:
        reachable = check_connectivity(settings)
        state['last_connectivity'] = now_iso()
        actions.append(f'connectivity: {"reachable" if reachable else "unreachable"}')
        # A run held back because Sonarr was unreachable goes as soon as it answers.
        if reachable and state.get('pending_run'):
            state['pending_run'] = None
            save_job_state(settings, state)
            actions.append('released the run that was waiting for Sonarr')
            with contextlib.suppress(Rejected):
                with run_lock():
                    run(preview=False, scheduled=True)
            state = job_state(settings)
            state['last_run'] = now_iso()

    # One reading a day, and the interface answers from it until the next one. Nothing
    # else here goes to Sonarr: a page open, a rule edited, a keep window widened are all
    # arithmetic over what this left behind.
    if sync_is_due(settings):
        with contextlib.suppress(Rejected, SonarrError):
            with run_lock():
                report = sync_from_sonarr(settings, reason='due')
            actions.append(f'synced with Sonarr: {report["series_changed"]} series changed')

    if schedules.is_due(settings.get('schedule') or {}, now, state.get('last_run')):
        if not sonarr_reachable(settings):
            # Queued rather than skipped: exactly one pending run, so an outage over a
            # weekend produces one catch-up rather than a backlog.
            state['pending_run'] = now_iso()
            actions.append('run queued: Sonarr is unreachable')
        else:
            # Reconcile immediately before acting. The stored reading is what the plan was
            # built from, and a run is the one moment that must not act on it blind.
            with contextlib.suppress(Rejected, SonarrError):
                sync_from_sonarr(settings, reason='before the run')
            state['last_run'] = now_iso()
            save_job_state(settings, state)
            actions.append('scheduled run')
            with contextlib.suppress(Rejected):
                with run_lock():
                    run(preview=False, scheduled=True)
            state = job_state(settings)
            state['last_run'] = now_iso()

    save_job_state(settings, state)
    for message in actions:
        log_line(settings, 'verbose', f'tick: {message}')
    if not actions:
        log_line(settings, 'verbose', 'tick: nothing due')
    return 0



def monitoring_for(settings: dict, rule: dict, force: bool = False, offline: bool = False) -> dict:
    """Everything one check knows about a series: monitoring, lifecycle, and the plan.

    Entirely from Sonarr. Sizes, air dates, import dates, monitoring and season numbers all
    arrive with the episodes, so this touches no filesystem and needs no path mapping.

    The episodes come from the store unless `force` is set or they have aged out, so
    re-deciding what a rule would do costs nothing. Everything below the fetch is
    arithmetic, and it is redone every time.
    """
    base = {'rule_id': rule['id'], 'series_title': rule.get('series_title') or rule['path'], 'ok': True}
    if rule.get('match_status') != 'matched':
        return dict(base, ok=False, error=rule.get('match_error') or 'Rule is not matched to a Sonarr series',
                    status='unmatched', label='Not matched to Sonarr')
    try:
        active = effective_rule(rule, settings.get('profiles'))
        episodes, series, read_at, from_cache = episodes_for(settings, rule, force=force, offline=offline)
    except Rejected as error:
        return dict(base, ok=False, error=str(error), status='unmatched', label='Could not read Sonarr')

    state = dict(base, **classify_monitoring(episodes, active, settings))
    # The age shown is the age of the reading, not of the arithmetic over it: the plan is
    # always current, and saying so about the data behind it would be a lie.
    state['read_at'] = read_at
    state['from_cache'] = from_cache
    if series:
        state.update(describe_lifecycle(state, series))

    present = [episode for episode in episodes if episode.get('has_file')]
    decision = evaluate(present, active, settings)
    would_delete = decision['delete']
    deleting = {item.get('episode_id') for item in would_delete}
    outside = state.get('out_frame_monitored') or []
    targets = monitoring_targets(settings, state, rule)
    # Deleting always unmonitors, and the run also unmonitors everything else outside the
    # window; both are counted here because both are changes someone would want to see.
    unmonitor = {row.get('episode_id') for row in outside} | deleting
    monitor = {row['episode_id'] for row in targets['monitor_list'] if row.get('episode_id')}
    state['plan'] = {
        'delete': len(would_delete),
        'delete_bytes': sum(int(item.get('size') or 0) for item in would_delete),
        'blocked': decision['blocked'] or '',
        'unmonitor': len([row for row in outside if row.get('episode_id') in unmonitor]),
        'unmonitor_missing': targets['unmonitor_missing'],
        'monitor': len(monitor),
        'mode': monitoring_mode(settings, rule),
        'computed_at': now_iso(),
    }
    return state



def check_recycle_bin(settings: dict, instance: dict) -> str:
    """Sonarr's recycle bin path, or '' when it has none. Cached with the instance state."""
    try:
        media = Sonarr(instance)._request('GET', 'config/mediamanagement') or {}
        return str(media.get('recycleBin') or '')
    except (SonarrError, Rejected):
        return ''


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def cli() -> int:
    parser = argparse.ArgumentParser(description='TV Retention worker')
    sub = parser.add_subparsers(dest='command', required=True)
    sub.add_parser('rpc', help='read one JSON request on stdin, write one JSON reply')
    run_parser = sub.add_parser('run', help='evaluate rules and delete')
    run_parser.add_argument('--scheduled', action='store_true')
    run_parser.add_argument('--preview', action='store_true')
    sub.add_parser('preview', help='evaluate rules without deleting')
    check_parser = sub.add_parser('check', help='verify Sonarr, matches, folders and monitoring')
    check_parser.add_argument('--scheduled', action='store_true')
    sub.add_parser('tick', help='decide what is due and run it (called every minute by cron)')
    sub.add_parser('resume', help='re-publish the cron entry after a reboot or array start')
    sub.add_parser('stop', help='no-op placeholder kept for symmetry with array events')
    args = parser.parse_args()

    if args.command == 'rpc':
        try:
            request = json.loads(sys.stdin.read() or '{}')
        except json.JSONDecodeError:
            print(json.dumps({'ok': False, 'error': 'Malformed request'}))
            return 0
        # Imported here, not at the top: actions imports this module, and dispatching is
        # the only thing that needs it, so the dependency stays one way.
        from actions import dispatch
        print(json.dumps(dispatch(request if isinstance(request, dict) else {}), ensure_ascii=False))
        return 0
    if args.command in ('run', 'preview'):
        preview = args.command == 'preview' or getattr(args, 'preview', False)
        try:
            with run_lock(blocking=False):
                result = run(preview=preview, scheduled=getattr(args, 'scheduled', False))
        except Rejected as error:
            print(f'TV Retention: {error}', file=sys.stderr)
            return 1
        verb = 'would delete' if result['dry_run'] else 'deleted'
        print(f'TV Retention {verb} {result["planned"] if result["dry_run"] else result["deleted"]} files '
              f'across {len(result["rules"])} rules in {result["duration_seconds"]}s')
        for message in result['errors'] + result['blocked']:
            print(f'  ! {message}')
        return 0
    if args.command == 'tick':
        return tick()
    if args.command == 'check':
        try:
            with run_lock(blocking=False):
                health = run_health_check(scheduled=getattr(args, 'scheduled', False))
        except Rejected as error:
            print(f'TV Retention: {error}', file=sys.stderr)
            return 1
        summary = alerts.summarise(health.get('alerts'))
        print(f'TV Retention checked {health.get("rules_checked", 0)} rule(s) in '
              f'{health.get("duration_seconds", 0)}s; {summary["error"]} error(s), '
              f'{summary["warning"]} warning(s)')
        for alert in health.get('alerts') or []:
            if alert['severity'] != alerts.NOTICE:
                print(f'  {alert["severity"]}: {alert["title"]} — {alert["detail"]}')
        return 0
    if args.command == 'resume':
        with contextlib.suppress(Rejected):
            write_cron(load_settings())
        return 0
    return 0


if __name__ == '__main__':
    sys.exit(cli())
